/**
 * Référentiel géographique Bénin embarqué — utilisé si l'API renvoie une liste vide.
 */
export const BENIN_DEPARTMENTS = [
  {
    "department": "Alibori",
    "communes": [
      "Banikoara",
      "Gogounou",
      "Kandi",
      "Karimama",
      "Malanville",
      "Ségbana"
    ]
  },
  {
    "department": "Atacora",
    "communes": [
      "Boukoumbé",
      "Cobly",
      "Kérou",
      "Kouandé",
      "Matéri",
      "Natitingou",
      "Péhunco",
      "Tanguiéta",
      "Toucountouna"
    ]
  },
  {
    "department": "Atlantique",
    "communes": [
      "Abomey-Calavi",
      "Allada",
      "Kpomassè",
      "Ouidah",
      "Sô-Ava",
      "Toffo",
      "Tori-Bossito",
      "Zè"
    ]
  },
  {
    "department": "Borgou",
    "communes": [
      "Bembéréké",
      "Kalalé",
      "N'Dali",
      "Nikki",
      "Parakou",
      "Pèrèrè",
      "Sinendé",
      "Tchaourou"
    ]
  },
  {
    "department": "Collines",
    "communes": [
      "Bantè",
      "Dassa-Zoumè",
      "Glazoué",
      "Ouèssè",
      "Savalou",
      "Savè"
    ]
  },
  {
    "department": "Couffo",
    "communes": [
      "Aplahoué",
      "Djakotomey",
      "Dogbo",
      "Klouékanmè",
      "Lalo",
      "Toviklin"
    ]
  },
  {
    "department": "Donga",
    "communes": [
      "Bassila",
      "Copargo",
      "Djougou",
      "Ouaké"
    ]
  },
  {
    "department": "Littoral",
    "communes": [
      "Cotonou"
    ]
  },
  {
    "department": "Mono",
    "communes": [
      "Athiémé",
      "Bopa",
      "Comè",
      "Grand-Popo",
      "Houéyogbé",
      "Lokossa"
    ]
  },
  {
    "department": "Ouémé",
    "communes": [
      "Adjarra",
      "Adjohoun",
      "Aguégués",
      "Akpro-Missérété",
      "Avrankou",
      "Bonou",
      "Dangbo",
      "Porto-Novo",
      "Sèmè-Kpodji"
    ]
  },
  {
    "department": "Plateau",
    "communes": [
      "Adja-Ouèrè",
      "Ifangni",
      "Kétou",
      "Pobè",
      "Sakété"
    ]
  },
  {
    "department": "Zou",
    "communes": [
      "Abomey",
      "Agbangnizoun",
      "Bohicon",
      "Covè",
      "Djidja",
      "Ouinhi",
      "Za-Kpota",
      "Zagnanado",
      "Zogbodomey"
    ]
  }
];

export const BENIN_DISTRICTS_BY_COMMUNE = {
  "Banikoara": [
    "Banikoara",
    "Founougo",
    "Gomparou",
    "Goumori",
    "Kokey",
    "Kokiborou",
    "Ounet",
    "Sompérékou",
    "Soroko",
    "Toura"
  ],
  "Gogounou": [
    "Bagou",
    "Gogounou",
    "Gounarou",
    "Ouara",
    "Sori",
    "Zoungou-Pantrossi"
  ],
  "Kandi": [
    "Angaradébou",
    "Bensékou",
    "Donwari",
    "Kandi I",
    "Kandi II",
    "Kandi III",
    "Kassakou",
    "Saah",
    "Sam",
    "Sonsoro"
  ],
  "Karimama": [
    "Birni Lafia",
    "Bogo-Bogo",
    "Karimama",
    "Kompa",
    "Monsey"
  ],
  "Malanville": [
    "Garou",
    "Guéné",
    "Madécali",
    "Malanville",
    "Toumboutou"
  ],
  "Ségbana": [
    "Libantè",
    "Liboussou",
    "Lougou",
    "Segbana",
    "Sokotindji"
  ],
  "Boukoumbé": [
    "Boukoumbé",
    "Dipoli",
    "Korontière",
    "Kossoucoingou",
    "Manta",
    "Natta",
    "Tabota"
  ],
  "Cobly": [
    "Cobly",
    "Datori",
    "Kountori",
    "Tapoga"
  ],
  "Kérou": [
    "Brignamaro",
    "Firou",
    "Kérou",
    "Koabagou"
  ],
  "Kouandé": [
    "Birni",
    "Chabi-Couma",
    "Fô-Tancé",
    "Guilmaro",
    "Kouandé",
    "Oroukayo"
  ],
  "Matéri": [
    "Dassari",
    "Gouandé",
    "Matéri",
    "Nodi",
    "Tantéga",
    "Tchianhoun-Cossi"
  ],
  "Natitingou": [
    "Kotopounga",
    "Kouaba",
    "Koundata",
    "Natitingou I",
    "Natitingou II",
    "Natitingou III",
    "Natitingou IV",
    "Perma",
    "Tchoumi-Tchoumi"
  ],
  "Péhunco": [
    "Gnémasson",
    "Péhunco",
    "Tobré"
  ],
  "Tanguiéta": [
    "Cotiakou",
    "N'Dahonta",
    "Taiakou",
    "Tanguiéta",
    "Tanongou"
  ],
  "Toucountouna": [
    "Kouarfa",
    "Tampégré",
    "Toucountouna"
  ],
  "Abomey-Calavi": [
    "Abomey-Calavi",
    "Akassato",
    "Cité Houéyiho",
    "Cocotiers",
    "Glo-Djigbé",
    "Godomey",
    "Hêvié",
    "Kpanroun",
    "Ouèdo",
    "Tankpè",
    "Togba",
    "Tokpa-Zoungo",
    "Zinvié",
    "Zogbadjè"
  ],
  "Allada": [
    "Agbanou",
    "Ahouannonzoun",
    "Allada",
    "Attogon",
    "Avakpa",
    "Ayou",
    "Hinvi",
    "Lissègazoun",
    "Lon-Agonmey",
    "Sekou",
    "Togoudo",
    "Tokpa-Avagoudo"
  ],
  "Kpomassè": [
    "Aganmalomè",
    "Agbanto",
    "Agonkanmè",
    "Dédomè",
    "Dékanmè",
    "Kpomassè",
    "Sègbèya",
    "Sègbohouè",
    "Tokpa-Domè"
  ],
  "Ouidah": [
    "Avlékété",
    "Djègbadji",
    "Gakpé",
    "Houakpè-Daho",
    "Ouidah I",
    "Ouidah II",
    "Ouidah III",
    "Ouidah IV",
    "Pahou",
    "Savi"
  ],
  "Sô-Ava": [
    "Ahomey-Lokpo",
    "Dékanmey",
    "Ganvié I",
    "Ganvié II",
    "Houédo-Aguékon",
    "Sô-Ava",
    "Vekky"
  ],
  "Toffo": [
    "Agué",
    "Colli-Agbamè",
    "Coussi",
    "Damè",
    "Djanglanmè",
    "Houègbo",
    "Kpomè",
    "Sè",
    "Sèhouè",
    "Toffo-Agué"
  ],
  "Tori-Bossito": [
    "Avamè",
    "Azohouè-Aliho",
    "Azohouè-Cada",
    "Tori acadjamè",
    "Tori aïdohoue",
    "Tori-Bossito",
    "Tori-Cada",
    "Tori-Gare"
  ],
  "Zè": [
    "Adjan",
    "Dawè",
    "Djigbé",
    "Dodji-Bata",
    "Hèkanmé",
    "Koundokpoé",
    "Sèdjè-Dénou",
    "Sèdjè-Houégoudo",
    "Tangbo-Djevié",
    "Yokpo",
    "Zè"
  ],
  "Bembéréké": [
    "Bembéréké",
    "Béroubouay",
    "Bouanri",
    "Gamia",
    "Ina"
  ],
  "Kalalé": [
    "Basso",
    "Bouka",
    "Dérassi",
    "Dunkassa",
    "Kalalé",
    "Péonga"
  ],
  "N'Dali": [
    "Bori",
    "Gbégourou",
    "N'Dali",
    "Ouénou",
    "Sirarou"
  ],
  "Nikki": [
    "Biro",
    "Gnonkourakali",
    "Nikki",
    "Ouénou",
    "Sérékalé",
    "Suya",
    "Tasso"
  ],
  "Parakou": [
    "1er arrondissement",
    "2e arrondissement",
    "3e arrondissement",
    "Agba agba",
    "Alaga",
    "Albarika",
    "Amanwignon",
    "Assagbinin- Baka",
    "Bakinkoura",
    "Bakounourou",
    "Bakpérou",
    "Banikanni",
    "Banikanni-Douwérou",
    "Banikanni-ENI",
    "Banikanni-Madjatom",
    "Baparapé",
    "Bèyarou",
    "Bosso-Camps-Peulhs",
    "Boundarou",
    "Camp-Adagbè",
    "Damagourou",
    "Dépôt",
    "Dokparou",
    "Gaanon",
    "Gah",
    "Ganou",
    "Gbira",
    "Goromosso",
    "Gounin",
    "Guéma",
    "Kabassira",
    "Kadéra",
    "Korobororou",
    "Korobororou-Peulh",
    "Kpébié",
    "Kpérou-Guéra",
    "Ladjifarani",
    "Ladjifarani-Petit Père",
    "Lémanda",
    "Madina",
    "Monnon",
    "Nikkikpérou",
    "Nima-Sokounon",
    "Ouézé",
    "Rose-Croix Bah Mora",
    "Sawararou",
    "Sinagourou",
    "Sourou",
    "Swinrou-Kpassagambou",
    "Thian",
    "Titirou",
    "Tourou-Dispensaire",
    "Tourou-Palais-Royal",
    "Tranza",
    "Wansirou",
    "Woré",
    "Worou-Tokorou",
    "Woubékou-Gah",
    "Zazira",
    "Zongo",
    "Zongo-Zénon"
  ],
  "Pèrèrè": [
    "Gninsy",
    "Guinagourou",
    "Kpané",
    "Pébié",
    "Pèrèrè",
    "Sontou"
  ],
  "Sinendé": [
    "Fô-Bourè",
    "Sèkèrè",
    "Sikki",
    "Sinendé"
  ],
  "Tchaourou": [
    "Alafiarou",
    "Bétérou",
    "Goro",
    "Kika",
    "Sanson",
    "Tchaourou",
    "Tchatchou"
  ],
  "Bantè": [
    "Agoua",
    "Akpassi",
    "Atokoligbé",
    "Bantè",
    "Bobè",
    "Gouka",
    "Koko",
    "Lougba",
    "Pira"
  ],
  "Dassa-Zoumè": [
    "Akofodjoulè",
    "Dassa I",
    "Dassa II",
    "Gbaffo",
    "Kerè",
    "Kpingni",
    "Lèma",
    "Paouignan",
    "Soclogbo",
    "Tré"
  ],
  "Glazoué": [
    "Aklankpa",
    "Assanté",
    "Glazoué",
    "Gomè",
    "Kpakpaza",
    "Magoumi",
    "Ouèdèmè",
    "Sokponta",
    "Thio",
    "Zaffé"
  ],
  "Ouèssè": [
    "Challa-Ogoi",
    "Djègbè",
    "Gbanlin",
    "Kémon",
    "Kilibo",
    "Laminou",
    "Odougba",
    "Toui"
  ],
  "Savalou": [
    "Djaloukou",
    "Doumè",
    "Gobada",
    "Kpataba",
    "Lahotan",
    "Lèma",
    "Logozohè",
    "Monkpa",
    "Ottola",
    "Ouèssè",
    "Savalou-aga",
    "Savalou-agbado",
    "Savalou-attakè",
    "Tchetti"
  ],
  "Savè": [
    "Adido",
    "Bèssè",
    "Boni",
    "Kaboua",
    "Ofè",
    "Okpara",
    "Plateau",
    "Sakin"
  ],
  "Bassila": [
    "Alédjo",
    "Bassila",
    "Manigri",
    "Pénéssoulou"
  ],
  "Copargo": [
    "Anandana",
    "Copargo",
    "Pabégou",
    "Singré"
  ],
  "Djougou": [
    "Barei",
    "Bariénou",
    "Bélléfoungou",
    "Bougou",
    "Djougou I",
    "Djougou II",
    "Djougou III",
    "Kolokondé",
    "Onklou",
    "Patargo",
    "Pélébina",
    "Sérou"
  ],
  "Ouaké": [
    "Badjoudè",
    "Kondé",
    "Ouaké",
    "Sèmèrè I",
    "Sèmèrè II",
    "Tchalinga"
  ],
  "Aplahoué": [
    "Aplahoué",
    "Atomè",
    "Azovè",
    "Dekpo",
    "Kissamey",
    "Lonkly"
  ],
  "Djakotomey": [
    "Adjintimey",
    "Bètoumey",
    "Djakotomey I",
    "Djakotomey II",
    "Gohomey",
    "Houègamey",
    "Kinkinhoué",
    "Kokohoué",
    "Kpoba",
    "Sokouhoué"
  ],
  "Dogbo": [
    "Ayomi",
    "Dèvè",
    "Honton",
    "Lokogohoué",
    "Madjrè",
    "Tota",
    "Totchagni"
  ],
  "Klouékanmè": [
    "Adjanhonmè",
    "Ahogbèya",
    "Aya-Hohoué",
    "Djotto",
    "Hondji",
    "Klouékanmè",
    "Lanta",
    "Tchikpé"
  ],
  "Lalo": [
    "Adoukandji",
    "Ahomadegbe",
    "Ahondjinnako",
    "Banigbé",
    "Gnizounmè",
    "Hlassamè",
    "Lalo",
    "Lokogba",
    "Tchito"
  ],
  "Toviklin": [
    "Avédjin",
    "Houédogli",
    "Toviklin"
  ],
  "Cotonou": [
    "10e arrondissement",
    "11e arrondissement",
    "12e arrondissement",
    "13e arrondissement",
    "1er arrondissement",
    "2e arrondissement",
    "3e arrondissement",
    "4e arrondissement",
    "5e arrondissement",
    "6e arrondissement",
    "7e arrondissement",
    "8e arrondissement",
    "9e arrondissement",
    "Abokicodji Centre",
    "Abokicodji Lagune",
    "Adjaha- Cité",
    "Adjégounlè",
    "Adogléta",
    "Agbato",
    "Agbodjèdo",
    "Agbodjèdo S",
    "Agla",
    "Agla-Agongbomey",
    "Agla-Akplomey",
    "Agla-Figaro",
    "Agla-Finafa",
    "Agla-les Pylônes",
    "Agla-Petit Château",
    "Agla-Sud",
    "Agontinkon",
    "Agounvocodji",
    "Ahogbohouè-Cité de l’expérience",
    "Ahogbohouè-Cité Eucaristie",
    "Ahouanlèko",
    "Ahouansori Agata",
    "Ahouansori Agué",
    "Ahouansori Ladji",
    "Ahouansori Towéta",
    "Ahouansori Towéta Kpota",
    "Ahouassa",
    "Aibatin dodo",
    "Aibatin Kpota",
    "Aidjèdo",
    "Aidjèdo Ahito",
    "Aidjèdo Gbègo",
    "Aidjèdo Vignon",
    "Akogbato",
    "Akpakpa",
    "Akpakpa Dodomè",
    "Avlékété Jonquet",
    "Avotrou Aïmonlonfidé",
    "Avotrou Gbègo",
    "Avotrou Houézèkomè",
    "Ayélawadjè",
    "Ayélawadjè Agongomè",
    "Bocossi Tokpa",
    "Cadjehoun",
    "Cadjèhoun Agonga",
    "Cadjèhoun Aupiais",
    "Cadjèhoun Azalokogon",
    "Cadjèhoun Détinsa",
    "Cadjèhoun Gare",
    "Cadjèhoun Kpota",
    "Cocotiers",
    "Dagbédji-Sikê",
    "Dandji",
    "Dandji Hokanmè",
    "Dantokpa",
    "Dédokpo",
    "Djèdjè-Layé",
    "Djidjè",
    "Djidjè Aïchédji",
    "Donaten",
    "Dota",
    "Enagnon",
    "Enagnon-Sikê",
    "Fidjrossè",
    "Fifadji",
    "Fifadji Houto",
    "Fifatin",
    "Fignon-Sikê",
    "Finagnon",
    "Fiyégnon Jacquot",
    "Gankpodo",
    "Gbèdagba",
    "Gbèdégbé",
    "Gbèdiga Guêdêhoungue",
    "Gbèdjèwin",
    "Gbèdjromèdé",
    "Gbèdjromèdé Sud",
    "Gbédokpo",
    "Gbèdomidji",
    "Gbégamey",
    "Gbégamey Ahito",
    "Gbégamey Centre",
    "Gbégamey Dodo Ayidjè",
    "Gbégamey Gbagoudo",
    "Gbégamey Mifongou",
    "Gbènan",
    "Gbénonkpo",
    "Gbéto",
    "Godomey-plage",
    "Guinkomey",
    "Haie-Vive",
    "Hindé Nord",
    "Hindé Sud",
    "Hlacomey",
    "Houéhoun",
    "Houénoussou",
    "Houénoussou S",
    "Houéyiho",
    "Houéyiho Tanou",
    "Irédé",
    "Jéricho",
    "Jéricho Nord",
    "Jéricho Sud",
    "Kindonou",
    "Kouhounou",
    "Kowégbo",
    "Kpankpan",
    "Kpondéhou",
    "Kpondéhou Tchémè",
    "Les Cocotiers",
    "Lom-Nava",
    "Mèdédjro",
    "Mènontin",
    "Midédji",
    "Midombo",
    "Mifongou",
    "Minonkpo Wologuèdè",
    "Minontchou",
    "Missèbo",
    "Missèkplé",
    "Missessin",
    "Missité",
    "Missité-Sikê",
    "Missogbé",
    "N’vènamèdé",
    "Nouveau Pont",
    "Ohe",
    "Saint Jean Gbèdiga",
    "Sainte-Rita",
    "Sèdami",
    "Sèdjro Saint Michel",
    "Sègbèya Nord",
    "Sègbèya Sud",
    "Sèhogan-Sikê",
    "Sènadé Sékou",
    "Sènandé",
    "Sètovi",
    "Sodjèatinmè Centre",
    "Sodjèatinmè Est",
    "Sodjèatinmè Ouest",
    "Suru Léré",
    "Tanto",
    "Tchanhounkpamè",
    "Todoté",
    "Tokpa Hoho",
    "Tokplégbé",
    "Tonato",
    "Védoko",
    "Vèdoko",
    "Vodjè Allobatin",
    "Vodjè Ayidoté",
    "Vodjè Centre",
    "Vodjè Finagnon",
    "Vodjè kpota",
    "Vossa",
    "Vossa-Kpodji",
    "Wlacodji",
    "Xwlacodji Kpodji",
    "Xwlacodji Plage",
    "Yagbé",
    "Yémicodji",
    "Yénawa",
    "Yénawa Daho",
    "Yénawa-Fifadji",
    "Yévèdo",
    "Zogbo",
    "Zogbohouè",
    "Zongo",
    "Zongo Ehuzu",
    "Zongo Nima"
  ],
  "Athiémé": [
    "Adohoun",
    "Atchannou",
    "Athiémé",
    "Dédékpoé",
    "Kpinnou"
  ],
  "Bopa": [
    "Agbodji",
    "Badazoui",
    "Bopa",
    "Gbakpodji",
    "Lobogo",
    "Possotomè",
    "Yégodoé"
  ],
  "Comè": [
    "Agatogbo",
    "Akodéha",
    "Comè",
    "Ouèdèmè-Pédah",
    "Oumako"
  ],
  "Grand-Popo": [
    "Adjaha",
    "Agoué",
    "Avloh",
    "Djanglanmey",
    "Gbéhoué",
    "Grand-Popo",
    "Sazoué"
  ],
  "Houéyogbé": [
    "Dahé",
    "Doutou",
    "Honhoué",
    "Houéyogbé",
    "Sè",
    "Zoungbonou"
  ],
  "Lokossa": [
    "Agamé",
    "Houin",
    "Koudo",
    "Lokossa",
    "Ouèdèmè"
  ],
  "Adjarra": [
    "Adjarra I",
    "Adjarra II",
    "Aglogbé",
    "Honvié",
    "Malanhoui",
    "Médédjonou"
  ],
  "Adjohoun": [
    "Adjohoun",
    "Akpadanou",
    "Awonou",
    "Azowlissè",
    "Dèmè",
    "Gangban",
    "Kodè",
    "Togbota"
  ],
  "Aguégués": [
    "Avagbodji",
    "Houédomè",
    "Zoungamè"
  ],
  "Akpro-Missérété": [
    "Akpro-Missérété",
    "Gomè-Sota",
    "Katagon",
    "Vakon",
    "Zodogbomey"
  ],
  "Avrankou": [
    "Atchoukpa",
    "Avrankou",
    "Djomon",
    "Gbozounmè",
    "Kouty",
    "Ouanho",
    "Sado"
  ],
  "Bonou": [
    "Affamè",
    "Atchonsa",
    "Bonou",
    "Damè-Wogon",
    "Houinviguè"
  ],
  "Dangbo": [
    "Dangbo",
    "Dèkin",
    "Gbéko",
    "Houédomey",
    "Hozin",
    "Késsounou",
    "Zounguè"
  ],
  "Porto-Novo": [
    "1er arrondissement",
    "2e arrondissement",
    "3e arrondissement",
    "4e arrondissement",
    "5e arrondissement",
    "Accron-Gogankomey",
    "Adjègounlè",
    "Adjina Nord",
    "Adjina Sud",
    "Adomey",
    "Agbokou Aga",
    "Agbokou Bassodji Mairie",
    "Agbokou Centre social",
    "Agbokou Odo",
    "Ahouantikomey",
    "Akonaboè",
    "Akpassa Odo Oba",
    "Anavié",
    "Anavié Voirie",
    "Attakè Olory-Togbé",
    "Attakè Yidi",
    "Avakpa Kpodji",
    "Avakpa-Tokpa",
    "Avassa Bagoro Agbokomey",
    "Ayétoro",
    "Ayimlonfidé",
    "Déguèkomè",
    "Djassin Daho",
    "Djassin Zounmè",
    "Djègan Daho",
    "Djègan kpèvi",
    "Djlado",
    "Dodji",
    "Donoukin Lissèssa",
    "Dota-Attingbansa-Azonzakomey",
    "Dowa",
    "Dowa Aliogbogo",
    "Dowa Dédomè",
    "Foun-Foun Djaguidi",
    "Foun-Foun Gbègo",
    "Foun-Foun Sodji",
    "Foun-Foun Tokpa",
    "Ganto",
    "Gbassou-Itabodo",
    "Gbêcon",
    "Gbèdjromèdé Fusion",
    "Gbèzounkpa",
    "Gbodjè",
    "Guévié",
    "Guévié Djèganto",
    "Guévié-Zinkomey",
    "Hassou Agué",
    "Hinkoudé",
    "Hlogou ou Hlongou",
    "Hondji-Honnou Filla",
    "Houègbo-Hlinkomey",
    "Houéyogbé-Gbèdji",
    "Houèzounmey",
    "Houinmè Château d’eau",
    "Houinmè Djaguidi",
    "Houinmè Ganto",
    "Houinmè Gbèdjromèdé",
    "Houinvié",
    "Hounsa",
    "Hounsouko",
    "Idi-Araba",
    "Iléfiè",
    "Kandévié Missogbé",
    "Kandévié Owodé",
    "Kandévié Radio Hokon",
    "Koutongbé",
    "Kpogbonmè",
    "Kpota Sandodo",
    "Lokossa",
    "Louho",
    "Oganla Atakpamè",
    "Oganla Sud",
    "Oganla-Gare-Est",
    "Ouando",
    "Ouando Clékanmè",
    "Ouando Kotin",
    "Ouinlinda Aholoukomey",
    "Ouinlinda Hôpital",
    "Sadognon-Adjégounlè",
    "Sadognon-Woussa",
    "Sagbo Kossoukodé",
    "Sèdjèko",
    "Sèto – Gbodjè",
    "Sokomey-Toffinkomey",
    "Tchinvié",
    "Togoh – Adankomey",
    "Tokpota Dadjrougbé",
    "Tokpota Davo",
    "Tokpota Vèdo",
    "Tokpota Zèbè",
    "Tokpota Zinlivali",
    "Vêkpa",
    "Zèbou –Itatigri",
    "Zèbou –Massè",
    "Zèbou Aga",
    "Zèbou Ahouangbo",
    "Zounkpa Houèto"
  ],
  "Sèmè-Kpodji": [
    "Agblangandan",
    "Aholouyèmè",
    "Djèrègbè",
    "Ekpè",
    "Sèmè-Kpodji",
    "Tohouè"
  ],
  "Adja-Ouèrè": [
    "Adja-Ouèrè",
    "Ikpinlè",
    "Kpoulou",
    "Massè",
    "Oko-Akarè",
    "Totonnoukon"
  ],
  "Ifangni": [
    "Banigbé",
    "Daagbé",
    "Ifangni",
    "Ko-Koumolou",
    "Lagbé",
    "Tchaada"
  ],
  "Kétou": [
    "Adakplamé",
    "Idigny",
    "Kétou",
    "Kpankou",
    "Odometa",
    "Okpometa"
  ],
  "Pobè": [
    "Ahoyéyé",
    "Igana",
    "Issaba",
    "Pobè",
    "Towé"
  ],
  "Sakété": [
    "Aguidi",
    "Ita-Djèbou",
    "Sakété I",
    "Sakété II",
    "Takon",
    "Yoko"
  ],
  "Abomey": [
    "Agbokpa",
    "Dètohou",
    "Djègbè",
    "Hounli",
    "Sèhoun",
    "Vidolè",
    "Zounzounmè"
  ],
  "Agbangnizoun": [
    "Adahondjigon",
    "Adingningon",
    "Agbangnizoun",
    "Kinta",
    "Kpota",
    "Lissazounmè",
    "Sahé",
    "Siwé",
    "Tanvé",
    "Zoungoudo"
  ],
  "Bohicon": [
    "Agongointo",
    "Avogbanna",
    "Bohicon I",
    "Bohicon II",
    "Gnidjazoun",
    "Lissèzoun",
    "Ouassaho",
    "Passagon",
    "Saclo",
    "Sodohomè"
  ],
  "Covè": [
    "Adogbé",
    "Gounli",
    "Houéko",
    "Houen-Hounso",
    "Lainta-Cogbè",
    "Naogon",
    "Soli",
    "Zogba"
  ],
  "Djidja": [
    "Agondji",
    "Agouna",
    "Dan",
    "Djidja",
    "Dohouimè",
    "Gobaix",
    "Houto",
    "Monsourou",
    "Mougnon",
    "Oungbègamè",
    "Setto",
    "Zoukon"
  ],
  "Ouinhi": [
    "Dasso",
    "Ouinhi",
    "Sagon",
    "Tohoué"
  ],
  "Za-Kpota": [
    "Allahé",
    "Assalin",
    "Houngomey",
    "Kpakpamè",
    "Kpozoun",
    "Za-Kpota",
    "Za-Tanta",
    "Zèko"
  ],
  "Zagnanado": [
    "Agonli-Houégbo",
    "Agonlin-Houégbo",
    "Banamè",
    "Don",
    "Dovi",
    "Kpédékpo",
    "Zagnanado",
    "Zoungado"
  ],
  "Zogbodomey": [
    "Akiza",
    "Avlamè",
    "Cana I",
    "Cana II",
    "Domè",
    "Koussoukpa",
    "Kpokissa",
    "Massi",
    "Tanwé-Hessou",
    "Zoukou"
  ]
};

export function getBeninDepartments() {
  return BENIN_DEPARTMENTS.map((entry) => ({
    department: entry.department,
    communes: [...entry.communes],
  }));
}

export function getBeninDistricts(commune) {
  if (!commune) return [];
  return [...(BENIN_DISTRICTS_BY_COMMUNE[commune] || [])];
}
